//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class UnityColorMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/UnityColor";
        public override string RosMessageName => k_RosMessageName;

        public string msg;

        public UnityColorMsg()
        {
            this.msg = "";
        }

        public UnityColorMsg(string msg)
        {
            this.msg = msg;
        }

        public static UnityColorMsg Deserialize(MessageDeserializer deserializer) => new UnityColorMsg(deserializer);

        private UnityColorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
        }

        public override string ToString()
        {
            return "UnityColorMsg: " +
            "\nmsg: " + msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
